// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/common/arrow/arrow_appender.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/arrow/arrow_converter.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/arrow/arrow_util.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/arrow/arrow_merge_event.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/arrow/arrow_query_result.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/arrow/arrow_wrapper.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/arrow/physical_arrow_collector.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/arrow/physical_arrow_batch_collector.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/arrow/schema_metadata.cpp>
