// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/common/types/row/partitioned_tuple_data.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/types/row/row_data_collection.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/types/row/row_data_collection_scanner.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/types/row/row_layout.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/types/row/tuple_data_allocator.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/types/row/tuple_data_collection.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/types/row/tuple_data_iterator.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/types/row/tuple_data_layout.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/types/row/tuple_data_scatter_gather.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/types/row/tuple_data_segment.cpp>
