// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/nested/binned_histogram.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/nested/list.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/nested/histogram.cpp>
