// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/main/extension/extension_alias.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/main/extension/extension_helper.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/main/extension/extension_install.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/main/extension/extension_load.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/main/extension/extension_util.cpp>
