// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/regression/regr_avg.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/regression/regr_count.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/regression/regr_slope.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/regression/regr_r2.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/regression/regr_sxx_syy.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/regression/regr_sxy.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/regression/regr_intercept.cpp>
