// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/function/scalar/operators/add.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/function/scalar/operators/arithmetic.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/function/scalar/operators/multiply.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/function/scalar/operators/subtract.cpp>
