// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/catalog/catalog_entry/dependency/dependency_entry.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/catalog/catalog_entry/dependency/dependency_subject_entry.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/catalog/catalog_entry/dependency/dependency_dependent_entry.cpp>
