// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/persistent/csv_rejects_table.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/persistent/physical_batch_copy_to_file.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/persistent/physical_batch_insert.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/persistent/physical_copy_database.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/persistent/physical_copy_to_file.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/persistent/physical_delete.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/persistent/physical_export.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/persistent/physical_insert.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/persistent/physical_update.cpp>
