// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/storage/metadata/metadata_manager.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/storage/metadata/metadata_reader.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/storage/metadata/metadata_writer.cpp>
