// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/common/serializer/binary_serializer.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/serializer/binary_deserializer.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/serializer/buffered_file_reader.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/serializer/buffered_file_writer.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/serializer/memory_stream.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/serializer/serializer.cpp>
