// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/storage/compression/numeric_constant.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/storage/compression/fixed_size_uncompressed.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/storage/compression/rle.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/storage/compression/dictionary_compression.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/storage/compression/string_uncompressed.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/storage/compression/uncompressed.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/storage/compression/validity_uncompressed.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/storage/compression/bitpacking.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/storage/compression/bitpacking_hugeint.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/storage/compression/patas.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/storage/compression/alprd.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/storage/compression/fsst.cpp>
