// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/transaction/duck_transaction_manager.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/transaction/duck_transaction.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/transaction/meta_transaction.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/transaction/undo_buffer.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/transaction/transaction_context.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/transaction/transaction.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/transaction/transaction_manager.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/transaction/commit_state.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/transaction/rollback_state.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/transaction/cleanup_state.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/transaction/wal_write_state.cpp>
