// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/test/appender/test_appender_abort.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/test/appender/test_appender.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/test/appender/test_concurrent_append.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/test/appender/test_appender_transactions.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/test/appender/test_nested_appender.cpp>
