// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/function/scalar/compressed_materialization_functions.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/function/scalar/generic_functions.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/function/scalar/string_functions.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/function/scalar/strftime_format.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/function/scalar/nested_functions.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/function/scalar/operators.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/function/scalar/pragma_functions.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/function/scalar/sequence_functions.cpp>
