// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/function/scalar/generic/binning.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/function/scalar/generic/constant_or_null.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/function/scalar/generic/getvariable.cpp>
