// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/generic/alias.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/generic/can_implicitly_cast.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/generic/current_setting.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/generic/error.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/generic/hash.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/generic/least.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/generic/stats.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/generic/typeof.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/generic/system_functions.cpp>
