// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/optimizer/compressed_materialization/compress_aggregate.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/optimizer/compressed_materialization/compress_comparison_join.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/optimizer/compressed_materialization/compress_distinct.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/optimizer/compressed_materialization/compress_order.cpp>
