// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/main/buffered_data/buffered_data.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/main/buffered_data/simple_buffered_data.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/main/buffered_data/batched_buffered_data.cpp>
