// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/test/sql/storage/test_buffer_manager.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/test/sql/storage/test_checksum.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/test/sql/storage/test_storage.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/test/sql/storage/test_database_size.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/test/sql/storage/wal_torn_write.cpp>
