// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/catalog/default/default_functions.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/catalog/default/default_generator.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/catalog/default/default_schemas.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/catalog/default/default_table_functions.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/catalog/default/default_types.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/catalog/default/default_views.cpp>
