// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/distributive/approx_count.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/distributive/arg_min_max.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/distributive/bitagg.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/distributive/bitstring_agg.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/distributive/bool.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/distributive/entropy.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/distributive/kurtosis.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/distributive/minmax.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/distributive/product.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/distributive/skew.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/distributive/string_agg.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/distributive/sum.cpp>
