// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/function/pragma/pragma_functions.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/function/pragma/pragma_queries.cpp>
