// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/common/exception/binder_exception.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/exception/catalog_exception.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/exception/conversion_exception.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/common/exception/parser_exception.cpp>
