// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/union/union_extract.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/union/union_tag.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/union/union_value.cpp>
