// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/list/array_slice.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/list/flatten.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/list/list_aggregates.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/list/list_filter.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/list/list_has_any_or_all.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/list/list_sort.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/list/list_distance.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/list/list_reduce.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/list/list_transform.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/list/list_value.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/scalar/list/range.cpp>
