// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/holistic/approx_top_k.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/holistic/quantile.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/holistic/mad.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/holistic/mode.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/holistic/approximate_quantile.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/holistic/reservoir_quantile.cpp>
