// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/algebraic/avg.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/algebraic/covar.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/algebraic/stddev.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/core_functions/aggregate/algebraic/corr.cpp>
