// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/projection/physical_projection.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/projection/physical_tableinout_function.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/projection/physical_pivot.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/projection/physical_unnest.cpp>
