// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/test/sql/parallelism/interquery/concurrent_checkpoint.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/test/sql/parallelism/interquery/test_concurrentappend.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/test/sql/parallelism/interquery/test_concurrentdelete.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/test/sql/parallelism/interquery/test_concurrent_dependencies.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/test/sql/parallelism/interquery/test_concurrent_index.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/test/sql/parallelism/interquery/test_concurrentupdate.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/test/sql/parallelism/interquery/test_concurrent_sequence.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/test/sql/parallelism/interquery/test_concurrent_prepared.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/test/sql/parallelism/interquery/test_default_catalog.cpp>
