// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/schema/physical_alter.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/schema/physical_attach.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/schema/physical_create_art_index.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/schema/physical_create_schema.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/schema/physical_create_type.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/schema/physical_create_sequence.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/schema/physical_create_table.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/schema/physical_create_view.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/schema/physical_create_function.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/schema/physical_detach.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/execution/operator/schema/physical_drop.cpp>
