// Unity Build generated by CMake
#include </home/nika/mini-pixels/pixels-duckdb/src/main/chunk_scan_state/query_result.cpp>
#include </home/nika/mini-pixels/pixels-duckdb/src/main/chunk_scan_state/batched_data_collection.cpp>
